### ISSUE TITLE
[JS] Add a quiz question on JSON.stringify usage of toJSON

### ISSUE THREAD

**Issue by nem035** [enkidevs/curriculum#889]
![image](https://user-images.githubusercontent.com/9661806/41935238-f3fd2dae-7956-11e8-877f-2863d9b1e411.png)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior

**Comment by EwaTrzemzalska** [comment]
I'd like to tackle on this one

**Comment by nem035** [comment]
Hi @EwaTrzemzalska, first of all, thanks for your interested 🙂 	

After looking it again, it seems that we do not have a piece of content relating directly to the `JSON.*` API.

Would you be open to writing an [insight](https://github.com/enkidevs/curriculum/wiki/Insight-Documentation)  called `json.md` in the  [javascript/core/objects](https://github.com/enkidevs/curriculum/tree/master/javascript/core/objects) [workout](https://github.com/enkidevs/curriculum/wiki/Workout-Documentation) that explains a little bit how [`JSON.stringify`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) and [`JSON.parse`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) work?

At the bottom of that insight, you can add this [Quiz question](https://github.com/enkidevs/curriculum/wiki/Insight-Documentation#quiz-question) as:

```md
...rest of the insight

---
## Quiz

<question goes here>
```

[Here's a complete insight](https://github.com/enkidevs/curriculum/blob/88c765610afa7ba316837bdfac55a628f7e956f6/javascript/core/dummy-workout/treating-a-boolean-as-number.md) you can use as an example.

If you don't feel like writing a full insight, [here's another example of an insight with just a quiz question](https://github.com/enkidevs/curriculum/blob/88c765610afa7ba316837bdfac55a628f7e956f6/javascript/core/dummy-workout/automatic-semicolon-insertion.md).

---

Note: for an insight to be actually included in a workout at a particular place, we also need to add its slug to the workout's readme.

For this case, we can add it at the end in `insights` section of the [README](https://github.com/enkidevs/curriculum/blob/master/javascript/core/objects/README.md):

```yml
name: Objects

description: An introduction to Objects in JavaScript

insights:
  - object-part-1
  - object-part-2
  - deleting-properties
  - keywords-in-hash-keys
  - hasownproperty-method
  - json // <---------------- add it here


exercises:
  - js-practice-objects
```
